import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import classNames from "classnames";
import { OUTSETA_OPTIONS } from "./_outseta";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Outseta + NextJS Demo",
  description: "Generated by create next app",
};

const outsetaOptionsAsJSString = JSON.stringify(OUTSETA_OPTIONS);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={classNames(inter.className, "h-full")}>
        {children}

        <Script id="outseta-options" strategy="beforeInteractive">
          {`var o_options = ${outsetaOptionsAsJSString};`}
        </Script>

        <Script
          id="outseta-script"
          src="https://cdn.outseta.com/outseta.min.js"
          strategy="beforeInteractive"
          data-options="o_options"
        />
      </body>
    </html>
  );
}
